"""
batch_commander.py — Headless CLI for evolutionary fitness-loop generation.

Two operating modes
-------------------
Free exploration (default)
    Decodes --prompt via SemanticCipher, locks genre, randomises everything
    else within genre-appropriate bounds.

Golden Matrix Injection  (--seed-pool PATH)
    Loads the top-5 winning parameter sets from a math_fitness_report.json
    produced by telemetry_grader_midi.  Each track is generated by sampling a
    golden matrix (score-weighted) and applying bounded mutation controlled by
    --mutation-factor (default 0.05 = tight; 0.20 = broad exploration).

Usage
-----
# Free exploration — 100 trap tracks
python -m src.orchestration.batch_commander \\
    --prompt "aggressive dark trap beat" \\
    --count 100 \\
    --outdir ./batch_output/trap

# Golden Matrix Injection — next evolutionary pass
python -m src.orchestration.batch_commander \\
    --prompt "aggressive dark trap beat" \\
    --count 100 \\
    --outdir ./batch_output/trap_gen2 \\
    --seed-pool ./batch_output/trap/math_fitness_report.json \\
    --mutation-factor 0.05
"""

from __future__ import annotations

import argparse
import json
import random
import time
from pathlib import Path
from typing import List, Optional

from src.composition.composition_engine import (
    CompositionEngine,
    GoldenMatrixPool,
    config_from_golden,
)
from src.composition.composition_config import CompositionConfig
from src.composition.genre_constants import GENRE_BPM, GENRE_SCALES
from src.generation.prompt_decoder import SemanticCipher

# Modular 10-track orchestrator -- preferred path for all new generation
try:
    from src.core.orchestrator import Orchestrator as _Orchestrator
    _ORC_AVAILABLE = True
except ImportError:
    _ORC_AVAILABLE = False

try:
    from src.export.utau_bridge import export as utau_export, RawNote
    _UTAU_OK = True
except ImportError:
    _UTAU_OK = False

# ── Constants ─────────────────────────────────────────────────────────────────

_ROOTS            = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
_TPQN             = 480
_PHRASE_GAP_TICKS = _TPQN * 4


# ── USTX helpers ─────────────────────────────────────────────────────────────

def _melody_to_raw_notes(melody_notes) -> list:
    notes = []
    for beat_pos, dur_beats, pitch, vel in melody_notes:
        tick = int(beat_pos * _TPQN)
        dur  = max(1, int(dur_beats * _TPQN))
        notes.append(RawNote(tick=tick, duration=dur, pitch=pitch, velocity=vel, lyric="la"))
    return notes


def _split_into_phrases(raw_notes: list) -> List[list]:
    if not raw_notes:
        return []
    raw_notes = sorted(raw_notes, key=lambda n: n.tick)
    phrases: List[list] = []
    current = [raw_notes[0]]
    for i in range(1, len(raw_notes)):
        prev = raw_notes[i - 1]
        curr = raw_notes[i]
        if curr.tick - (prev.tick + prev.duration) > _PHRASE_GAP_TICKS:
            phrases.append(current)
            current = []
        current.append(curr)
    if current:
        phrases.append(current)
    return [p for p in phrases if p]


# ── Metadata helpers ──────────────────────────────────────────────────────────

def _build_seed_info(engine: CompositionEngine, genre: str) -> dict:
    genre_list  = engine.genre_seeds.get(genre, [])
    sample_size = min(5, len(genre_list))
    sample_idx  = sorted(random.sample(range(len(genre_list)), sample_size)) if genre_list else []
    return {
        "seeds_dir":                 str(engine.seeds_dir),
        "total_loaded":              len(engine.seeds),
        "genre_seed_count":          len(genre_list),
        "genre_seed_indices_sample": sample_idx,
    }


# ── Config builders ───────────────────────────────────────────────────────────

def _config_free(target_genre: str, target_bpm: float, bpm_range: tuple,
                 target_scale: Optional[str], strict_scale: bool,
                 base_tension: float) -> tuple:
    """
    Build a randomly-mutated config for free-exploration mode.
    Returns (config, param_dict) so the ledger can record what was used.
    """
    mutated_bpm       = float(random.uniform(bpm_range[0], bpm_range[1]))
    mutated_root      = random.choice(_ROOTS)
    genre_scale_pool  = GENRE_SCALES.get(target_genre, ["major", "minor"])
    mutated_scale     = target_scale if strict_scale else random.choice(genre_scale_pool)
    mutated_key       = f"{mutated_root} {mutated_scale}"
    mutated_tension   = float(max(0.0, min(1.5, base_tension + random.uniform(-0.2, 0.2))))
    mutated_complexity= random.randint(3, 9)
    mutated_mutation  = round(random.uniform(0.1, 0.7), 3)
    mutated_humanize  = round(random.uniform(0.4, 0.9), 3)
    mutated_seed      = random.randint(0, 999_999)

    config = CompositionConfig(
        genre              = target_genre,
        bpm                = mutated_bpm,
        key                = mutated_key,
        complexity         = mutated_complexity,
        tension_multiplier = mutated_tension,
        mutation           = mutated_mutation,
        humanize_amount    = mutated_humanize,
        seed_value         = mutated_seed,
    )
    config.tracks['arp']['enabled'] = True

    params = {
        "genre":              target_genre,
        "bpm":                round(mutated_bpm, 2),
        "key":                mutated_key,
        "root":               mutated_root,
        "scale":              mutated_scale,
        "scale_locked":       strict_scale,
        "complexity":         mutated_complexity,
        "tension_multiplier": round(mutated_tension, 3),
        "mutation":           mutated_mutation,
        "seed_value":         mutated_seed,
        "humanize_amount":    mutated_humanize,
    }
    return config, params, None  # (config, params, golden_source)


def _config_from_pool(pool: GoldenMatrixPool) -> tuple:
    """
    Sample one golden matrix, apply bounded mutation, return
    (config, param_dict, golden_source_info).
    """
    golden = pool.sample()
    config = config_from_golden(golden, pool.mutation_factor)

    p = config  # shorthand
    params = {
        "genre":              p.genre,
        "bpm":                p.bpm,
        "key":                p.key,
        "root":               p.key.split()[0] if p.key else "C",
        "scale":              p.key.split()[1] if p.key and len(p.key.split()) > 1 else "major",
        "scale_locked":       True,
        "complexity":         p.complexity,
        "tension_multiplier": p.tension_multiplier,
        "mutation":           p.mutation,
        "seed_value":         p.seed_value,
        "humanize_amount":    p.humanize_amount,
    }
    golden_source = {
        "rank":       golden.get("rank"),
        "track_name": golden.get("track_name"),
        "score":      golden.get("score"),
        "mutation_factor": pool.mutation_factor,
    }
    return config, params, golden_source


# ── Core generation loop ──────────────────────────────────────────────────────

def run_batch(
    prompt:          str,
    count:           int,
    outdir:          str,
    seed:            Optional[int] = None,
    singer:          str = "TIGER DS",
    seeds_dir:       str = "seeds",
    seed_pool_path:  Optional[str] = None,
    mutation_factor: float = 0.05,
    vocal_mask:      bool = False,
) -> None:
    """
    Generate *count* tracks and write them to *outdir*.

    Parameters
    ----------
    prompt          : Natural-language description used to lock genre/scale
    count           : Number of tracks to produce
    outdir          : Root output directory (created if missing)
    seed            : Optional global RNG seed for reproducibility
    singer          : UTAU singer name embedded in .ustx files
    seeds_dir       : Path to the seeds directory for CompositionEngine
    seed_pool_path  : Path to math_fitness_report.json for golden injection
    mutation_factor : Jitter magnitude for golden injection (default 0.05)
    """
    out_path = Path(outdir)
    out_path.mkdir(parents=True, exist_ok=True)

    engine = CompositionEngine(seeds_dir=seeds_dir)
    engine.load_seeds()

    # Instantiate the modular orchestrator once; falls back to engine.compose() if unavailable
    _orc = _Orchestrator(engine) if _ORC_AVAILABLE else None

    # ── Decode prompt ─────────────────────────────────────────────────────────
    cipher      = SemanticCipher()
    base_params = cipher.decode_prompt(prompt)

    target_genre = base_params.genre or "pop"
    bpm_range    = GENRE_BPM.get(target_genre, (100, 130))
    target_bpm   = (
        base_params.bpm if base_params.bpm is not None
        else (bpm_range[0] + bpm_range[1]) / 2.0
    )
    target_scale   = base_params.scale_hint
    strict_scale   = target_scale is not None
    base_tension   = base_params.tension_multiplier if base_params.tension_multiplier is not None else 0.5
    base_complexity= base_params.complexity         if base_params.complexity         is not None else 5

    # ── Golden pool (optional) ────────────────────────────────────────────────
    pool: Optional[GoldenMatrixPool] = None
    if seed_pool_path:
        pool = GoldenMatrixPool.from_report(seed_pool_path, mutation_factor)
        # Override genre from pool's report if genre differs from prompt
        pool_genre = pool.matrices[0].get("generation_params", {}).get("genre")
        if pool_genre and pool_genre != target_genre:
            print(f"  [Pool] Genre override: {target_genre} -> {pool_genre}")
            target_genre = pool_genre

    if seed is not None:
        random.seed(seed)

    mode_label = f"golden injection  pool={pool.summary()}" if pool else \
                 f"free exploration  bpm~{target_bpm:.1f}  " \
                 f"scale={'locked:'+target_scale if strict_scale else 'flexible'}"

    print(f"Batch Commander — prompt: '{prompt}'")
    print(f"  genre={target_genre}  mode={mode_label}  count={count}")
    if not _UTAU_OK:
        print("  [INFO] USTX export disabled (mido/pyyaml not installed)")

    batch_tracks: list = []

    for i in range(count):
        track_name = f"track_{i:03d}"
        track_dir  = out_path / track_name
        track_dir.mkdir(exist_ok=True)

        # ── Build config ──────────────────────────────────────────────────────
        if pool is not None:
            config, gen_params, golden_source = _config_from_pool(pool)
        else:
            config, gen_params, golden_source = _config_free(
                target_genre, target_bpm, bpm_range,
                target_scale, strict_scale, base_tension,
            )
        config.vocal_mask = vocal_mask

        t_start = time.time()

        # ── Compose (10-track orchestrator → legacy fallback) ─────────────────
        try:
            if _orc is not None:
                comp = _orc.compose(config, seed_pool_path=seed_pool_path)
            else:
                comp = engine.compose(config)
        except Exception as exc:
            print(f"  [ERROR] Compose failed for {track_name}: {exc}")
            continue

        # Patch gen_params with actual BPM that engine used
        gen_params["bpm"] = comp["config"]["bpm"]

        # ── Export MIDI ───────────────────────────────────────────────────────
        midi_path = track_dir / f"{track_name}.mid"
        try:
            engine.export_midi(comp, str(midi_path))
        except Exception as exc:
            print(f"  [ERROR] MIDI export failed for {track_name}: {exc}")

        # ── Export USTX ───────────────────────────────────────────────────────
        ustx_path = track_dir / f"{track_name}.ustx"
        if _UTAU_OK:
            melody_notes = comp["tracks"].get("04_Melody", [])
            if melody_notes:
                try:
                    phrases = _split_into_phrases(_melody_to_raw_notes(melody_notes))
                    if phrases:
                        utau_export(
                            output_path = ustx_path,
                            phrases     = phrases,
                            tpqn        = _TPQN,
                            bpm         = comp["config"]["bpm"],
                            song_name   = track_name,
                            singer      = singer,
                        )
                except Exception as exc:
                    print(f"  [WARN] USTX export failed for {track_name}: {exc}")

        t_elapsed = round(time.time() - t_start, 3)

        # ── Intelligence ledger ───────────────────────────────────────────────
        track_note_counts = {k: len(v) for k, v in comp["tracks"].items()}
        total_notes       = sum(track_note_counts.values())
        render_seed       = gen_params["seed_value"]

        metadata: dict = {
            "track_index":       i,
            "render_seed":       render_seed,
            "prompt":            prompt,
            "prompt_decoded":    base_params.summary(),
            "generation_mode":   "golden_injection" if pool else "free_exploration",
            "generation_params": gen_params,
            "seed_info":         _build_seed_info(engine, target_genre),
            "outputs": {
                "midi_path":         str(midi_path.relative_to(out_path)),
                "ustx_path":         str(ustx_path.relative_to(out_path)) if ustx_path.exists() else None,
                "track_note_counts": track_note_counts,
                "total_notes":       total_notes,
            },
            "structure":          comp["structure"],
            "chord_progression":  comp["chord_progression"][:32],
            "generation_timestamp":        time.strftime("%Y-%m-%dT%H:%M:%S"),
            "generation_duration_seconds": t_elapsed,
            "vocal_mask_active":           getattr(config, 'vocal_mask', False),
        }
        if golden_source:
            metadata["golden_source"] = golden_source

        meta_path = track_dir / "generation_metadata.json"
        with open(meta_path, "w", encoding="utf-8") as fh:
            json.dump(metadata, fh, indent=2)

        batch_tracks.append({
            "track_index":   i,
            "track_name":    track_name,
            "render_seed":   render_seed,
            "bpm":           gen_params["bpm"],
            "key":           gen_params["key"],
            "total_notes":   total_notes,
            "golden_source": golden_source,
        })

        print(
            f"  [{i+1:>4}/{count}] {track_name}  bpm={gen_params['bpm']:.1f}"
            f"  key={gen_params['key']:<14}  notes={total_notes}"
            + (f"  [from #{golden_source['rank']} score={golden_source['score']:.1f}]"
               if golden_source else "")
            + f"  ({t_elapsed:.2f}s)"
        )

    # ── Batch manifest ────────────────────────────────────────────────────────
    manifest = {
        "prompt":          prompt,
        "count":           count,
        "generation_mode": "golden_injection" if pool else "free_exploration",
        "base_decoded":    base_params.summary(),
        "base_params": {
            "genre":              target_genre,
            "bpm":                round(target_bpm, 2),
            "scale":              target_scale,
            "scale_locked":       strict_scale,
            "tension_multiplier": round(base_tension, 3),
            "complexity":         base_complexity,
        },
        "golden_pool": {
            "report_path":     seed_pool_path,
            "mutation_factor": mutation_factor,
            "matrices_used":   len(pool.matrices) if pool else 0,
        } if pool else None,
        "tracks": batch_tracks,
    }
    manifest_path = out_path / "batch_manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print(f"\nDone. {len(batch_tracks)}/{count} tracks written to '{outdir}'")
    print(f"Manifest: {manifest_path}")


# ── CLI entry point ───────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="batch_commander",
        description="Music Architect — headless evolutionary batch generator",
    )
    parser.add_argument("--prompt",          required=True,
                        help="Natural-language track description")
    parser.add_argument("--count",           type=int, default=10,
                        help="Number of tracks to generate (default: 10)")
    parser.add_argument("--outdir",          default="./batch_output",
                        help="Output directory (default: ./batch_output)")
    parser.add_argument("--seed",            type=int, default=None,
                        help="Global RNG seed for reproducibility")
    parser.add_argument("--singer",          default="TIGER DS",
                        help="UTAU singer name (default: TIGER DS)")
    parser.add_argument("--seeds-dir",       default="seeds", dest="seeds_dir",
                        help="Path to seeds directory (default: seeds)")
    parser.add_argument("--seed-pool",       default=None, dest="seed_pool_path",
                        help="Path to math_fitness_report.json for golden injection")
    parser.add_argument("--mutation-factor", type=float, default=0.05,
                        dest="mutation_factor",
                        help="Mutation magnitude for golden injection "
                             "(0.05=tight, 0.20=broad; default: 0.05)")
    parser.add_argument("--vocal-mask", action="store_true", default=False,
                        dest="vocal_mask",
                        help="Enable vocal space mask (clears C4-C6 in verse/chorus)")

    args = parser.parse_args()
    run_batch(
        prompt          = args.prompt,
        count           = args.count,
        outdir          = args.outdir,
        seed            = args.seed,
        singer          = args.singer,
        seeds_dir       = args.seeds_dir,
        seed_pool_path  = args.seed_pool_path,
        mutation_factor = args.mutation_factor,
        vocal_mask      = args.vocal_mask,
    )


if __name__ == "__main__":
    main()
